### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by robmercier00** [wakatime/atom-wakatime#13]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [wakatime](https://github.com/wakatime/atom-wakatime) package, v4.0.7

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At ~/.atom/packages/wakatime/lib/wakatime.coffee:219

TypeError: Cannot read property 'length' of undefined
  at fileIsIgnored (~/.atom/packages/wakatime/lib/wakatime.coffee:219:5)
  at ~/.atom/packages/wakatime/lib/wakatime.coffee:197:68
  at pythonLocation (~/.atom/packages/wakatime/lib/wakatime.coffee:64:9)
  at sendHeartbeat (~/.atom/packages/wakatime/lib/wakatime.coffee:195:13)
  at ~/.atom/packages/wakatime/lib/wakatime.coffee:55:21
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:550:20)
  at BufferPatch.module.exports.BufferPatch.applyTo (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/buffer-patch.js:57:21)
  at Transaction.module.exports.Transaction.applyTo (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/transaction.js:70:15)
  at History.module.exports.History.abortTransaction (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/history.js:169:24)
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/history.js:126:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:647:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1157:26)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:440:35)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
     -2:19.3.0 application:open (atom-text-editor.editor)
     -1:12.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
 13x -1:11.3.0 core:confirm (atom-text-editor.editor.mini)
     -0:31.5.0 core:close (atom-text-editor.editor.is-focused)
     -0:26.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  9x -0:25.8.0 core:confirm (atom-text-editor.editor.mini)
     -0:02.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:02.1.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "wrap-guide",
      "welcome",
      "language-sql-mysql"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "wakatime": {
    "apikey": "35a2b644-1166-4749-a41a-4ab86f4b06ca"
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.8.0
wakatime, v4.0.7

# Dev
No dev packages
```

**Comment by alanhamlett** [comment]
You will need to generate a new api key, since your config includes your secret api key:
https://wakatime.com/settings

I've released a new version 4.0.8 of the plugin to fix this issue.

**Comment by alanhamlett** [comment]
BTW, thanks for helping. Let me know if anything else comes up.

**Comment by robmercier00** [comment]
I generated a new API key, entered the new API Key into the Atom package settings, and I'm still getting the error. Tried disabling other installed packages and reverted to the default UI & Syntax themes, doesn't seem to make a difference.

**Comment by robmercier00** [comment]
Got it working. Had to completely remove my API key, then quit & restart Atom. Opened up the package settings, re-entered my new API key, and it worked. Thanks for the great work Alan!

**Comment by alanhamlett** [comment]
:+1:

**Comment by MityaDSCH** [comment]
Atom Version: 1.2.4
System: Mint 17.2
Thrown From: wakatime package, v6.0.5

Now I'm getting the same error: 
```
~/.atom/packages/wakatime/lib/wakatime.coffee:449
TypeError: Cannot read property 'length' of undefined
    at fileIsIgnored (/home/myles/.atom/packages/wakatime/lib/wakatime.coffee:449:3)
    at sendHeartbeat (/home/myles/.atom/packages/wakatime/lib/wakatime.coffee:380:50)
    at /home/myles/.atom/packages/wakatime/lib/wakatime.coffee:207:11
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextEditor.module.exports.TextEditor.cursorMoved (/opt/atom/resources/app.asar/src/text-editor.js:1579:27)
    at Selection.module.exports.Selection.markerDidChange (/opt/atom/resources/app.asar/src/selection.js:926:21)
    at /opt/atom/resources/app.asar/src/selection.js:41:24
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Marker.module.exports.Marker.notifyObservers (/opt/atom/resources/app.asar/src/marker.js:262:27)
    at /opt/atom/resources/app.asar/src/marker.js:63:26
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Marker.module.exports.Marker.emitChangeEvent (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:401:20)
    at Marker.module.exports.Marker.update (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:346:12)
    at Marker.module.exports.Marker.setHeadPosition (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:143:19)
    at Marker.module.exports.Marker.setHeadBufferPosition (/opt/atom/resources/app.asar/src/marker.js:173:32)
    at Marker.module.exports.Marker.setHeadScreenPosition (/opt/atom/resources/app.asar/src/marker.js:183:19)
    at /opt/atom/resources/app.asar/src/cursor.js:65:31
    at Cursor.module.exports.Cursor.changePosition (/opt/atom/resources/app.asar/src/cursor.js:674:7)
    at Cursor.module.exports.Cursor.setScreenPosition (/opt/atom/resources/app.asar/src/cursor.js:63:19)
    at /opt/atom/resources/app.asar/src/text-editor.js:1369:23
    at TextEditor.module.exports.TextEditor.moveCursors (/opt/atom/resources/app.asar/src/text-editor.js:1573:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/opt/atom/resources/app.asar/src/text-editor.js:1368:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/opt/atom/resources/app.asar/src/text-editor-component.js:666:25)
    at HTMLDivElement.<anonymous> (/opt/atom/resources/app.asar/src/text-editor-component.js:3:61)
```

Tried robmercier's api key replacement fix in ~/.wakatime.cfg and restart to no avail.Then tried uninstalling wakatime, closing atom, and replacing the key before restarting and reinstalling. Somehow still getting the same error.
